/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Surface = string;
export type ExampleEs = string;
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Region".
 */
export type Region = "neutral" | "ES" | "MX" | "AR" | "CO";
export type Regions = Region[];
export type Register = "coloquial" | "neutral" | "formal";
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "ConfidenceLabel".
 */
export type ConfidenceLabel = "high" | "med" | "low" | "unrated";
export type Seed = boolean;
export type Consistency = number | null;
export type Verifier = string | null;
export type Id = string;
export type Pattern = string;
export type Slots = string[];
export type Surface1 = string;
export type GlossEn = string;
export type Register1 = "coloquial" | "neutral" | "formal";
export type Regions1 = Region[];
export type Es = string;
export type En = string;
export type Highlight = number[] | null;
export type Verb = string;
export type Person = string;
export type Tense = string;
/**
 * Character range [start, end) of the chunk inside `translation`, computed by the service; null when no lemma-level match is found
 */
export type TranslationHighlight = number[] | null;
export type Alternatives = Alternative[];
export type Text = string;
export type SourceLang = string;
export type TargetLang = string;
export type Region1 = "neutral" | "ES" | "MX" | "AR" | "CO";
export type IncludeAlternatives = boolean;
export type ConfidenceMode = "fast" | "full";
export type RequestId = string;
export type Input = string;
export type Translation = string;
export type Chunks = Chunk[];
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "NoteKind".
 */
export type NoteKind =
  | "calque"
  | "false_friend"
  | "preposition"
  | "ser_estar"
  | "subjunctive_trigger"
  | "gender_or_article"
  | "register"
  | "other";
export type Avoid = string;
export type Why = string;
export type AppliesTo = string[];
export type Notes = Note[];
export type PromptVersion = string;
export type Model = string;
export type LatencyMs = number;
export type Cached = boolean;
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "ConfidenceMode".
 */
export type ConfidenceMode1 = "fast" | "full";
export type Code = string;
export type Message = string;
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Register".
 */
export type Register2 = "coloquial" | "neutral" | "formal";

/**
 * trozo chunk service API contract, generated from Pydantic. Do not edit.
 */
export interface TrozoChunkAPI {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Alternative".
 */
export interface Alternative {
  surface: Surface;
  example_es: ExampleEs;
  regions: Regions;
  register?: Register;
  confidence: Confidence;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Confidence".
 */
export interface Confidence {
  label: ConfidenceLabel;
  signals?: Signals;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Signals".
 */
export interface Signals {
  seed?: Seed;
  consistency?: Consistency;
  verifier?: Verifier;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Chunk".
 */
export interface Chunk {
  id: Id;
  pattern: Pattern;
  slots?: Slots;
  surface: Surface1;
  gloss_en: GlossEn;
  register?: Register1;
  regions?: Regions1;
  example: Example;
  translation_highlight?: TranslationHighlight;
  confidence: Confidence;
  alternatives?: Alternatives;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Example".
 */
export interface Example {
  es: Es;
  en: En;
  highlight?: Highlight;
  conjugation?: Conjugation | null;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Conjugation".
 */
export interface Conjugation {
  verb: Verb;
  person: Person;
  tense: Tense;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "ChunkRequest".
 */
export interface ChunkRequest {
  text: Text;
  source_lang?: SourceLang;
  target_lang?: TargetLang;
  preferred_region?: Region1;
  include_alternatives?: IncludeAlternatives;
  confidence_mode?: ConfidenceMode;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "ChunkResponse".
 */
export interface ChunkResponse {
  request_id: RequestId;
  input: Input;
  translation: Translation;
  chunks: Chunks;
  notes?: Notes;
  meta: Meta;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Note".
 */
export interface Note {
  kind: NoteKind;
  avoid: Avoid;
  why: Why;
  applies_to?: AppliesTo;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
  prompt_version: PromptVersion;
  model: Model;
  latency_ms: LatencyMs;
  cached: Cached;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  code: Code;
  message: Message;
}
/**
 * This interface was referenced by `TrozoChunkAPI`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface ErrorResponse {
  error: ErrorBody;
}
